---
title: "Graphs- Trial 1"
author: "Gracie White"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load packages and read in data 

library(tidyverse)

norep_noclim_df <- read_csv("norep_noclim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
nr_nc_df <- norep_noclim_df %>%
   mutate(parameters = paste0(paste0(paste0(paste0(paste0("r=", r), ", f="), f), ", err="), f_ratio_err)) %>% 
  group_by(id)

nr_nc_plot <- ggplot(nr_nc_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r)) +
  theme_bw()

nr_nc_plot

```


```{r}
norep_clim_df <- read_csv("norep_clim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
nr_c_df <- norep_clim_df %>%
   mutate(parameters = paste0(paste0(paste0(paste0(paste0("r=", r), ", f="), f), ", err="), f_ratio_err)) %>% 
  group_by(id) %>% 
  filter(f!=0) %>% 
  filter(r_s < 0 & r_s >= -0.007) 

nr_c_df$error <- as.factor(nr_c_df$error)

nr_c_plot <- ggplot(nr_c_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r_0)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "No Adaption + Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))

nr_c_plot

ggsave(filename="norep_clim.jpg", plot=last_plot())

```


```{r}
rep5_clim_df <- read_csv("rep5_clim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
r5_c_df <- rep5_clim_df %>% 
  group_by(id) %>% 
  filter(f!=0) %>% 
  filter(r_s < 0 & r_s >= -0.007) %>% 
  filter(error == 0.3)

r5_c_df$error <- as.factor(r5_c_df$error)
r5_c_df$r_s <- as.factor(r5_c_df$r_s)

r5_c_plot <- ggplot(r5_c_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r_0)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "5 Year Adaption + Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))

r5_c_plot

ggsave(filename="rep5_clim.jpg", plot=last_plot())
```



```{r}
rep10_clim_df <- read_csv("rep10_clim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
r10_c_df <- rep10_clim_df %>% 
  group_by(id) %>% 
  filter(f!=0) %>% 
  filter(r_s < 0 & r_s >= -0.007)%>% 
  filter(error == 0.3)

r10_c_df$error <- as.factor(r10_c_df$error)

r10_c_plot <- ggplot(r10_c_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r_0)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "10 Year Adaption + Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))


r10_c_plot

ggsave(filename="rep10_clim.jpg", plot=last_plot())
```


```{r}
rep15_clim_df <- read_csv("rep15_clim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
r15_c_df <- rep15_clim_df %>% 
  group_by(id) %>% 
  filter(f!=0) %>% 
  filter(r_s < 0 & r_s >= -0.007)%>% 
  filter(error == 0.3)

r15_c_df$error <- as.factor(r15_c_df$error)

r15_c_plot <- ggplot(r15_c_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r_0)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "15 Year Adaption + Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))


r15_c_plot

ggsave(filename="rep15_clim.jpg", plot=last_plot())
```


```{r}
rep20_clim_df <- read_csv("rep20_clim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
r20_c_df <- rep20_clim_df %>% 
  group_by(id) %>% 
  filter(f!=0) %>% 
  filter(r_s < 0 & r_s >= -0.007)%>% 
  filter(error == 0.3)

r20_c_df$error <- as.factor(r20_c_df$error)

r20_c_plot <- ggplot(r20_c_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r_0)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "20 Year Adaption + Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))


r20_c_plot
ggsave(filename="rep20_clim.jpg", plot=last_plot())
```




```{r}
rep10_noclim_df <- read_csv("rep10_noclim.csv")

#alter dataset slightly, may be unnecessary, but we shall see 
r10_nc_df <- rep10_noclim_df %>%
  group_by(id) %>% 
  mutate(initial_r = ifelse(r <= .3, "slow-growing", ifelse(r >.3 & r <= .5, "medium-growing", "fast-growing"))) %>% 
  filter(f>=.1)

r10_nc_plot <- ggplot(r10_nc_df, aes(x = year, y = b, group = id)) +
  geom_line(aes(color = r)) +
  theme_bw() +
  scale_color_continuous(low = "#079EDF", high = "#B8CE55", name = "Growth Rate") +
  labs(title = "10 Year Adaption, No Climate", y = "Biomass", x = "Year") +
  theme(axis.text.x=element_text(size=10), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold"), axis.title.y = element_text(face = "bold"))

r10_nc_plot
ggsave(filename="rep10_noclim.jpg", plot=last_plot())
```




```{r}

```

