---
title: "Pella Tomlinson Initial"
author: "Sara Orofino"
date: "10/7/2019"
output: html_document
---

Packages:
```{r packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(TMB)
```


Define the Pella Tomlinson (pt) Surplus Production Function:
```{r inital_model}

# Define the function
pt <- function(B_t, r, K, p, H){
  B_t <- B_t + (
    ((r/p) * B_t) *
      (1-((B_t/K) * exp(p)))
    ) - H
  return(B_t)
}

#Define initial parameters:
#Note these values of r are made up - not actually reflective of slow vs fast growing species; need to find this still
r_slow<- 0.1 #intrinsic growth rate for slow-growing species()
r_med <- 0.5 #intrinsic growth rate for medium-growing species ()
r_fast <- 0.8 #intrinsic growth rate for fast-growing species ()

K <- 10000 #carrying capacity (metric tons)
p <- 0.2 #shape parameter 

B0_under <- 0.6*K #initial biomass (metric tons) if stock is under exploited (60% or more of unfished biomass)
B0_full <- 0.5*K #initial biomass (metric tons) if stock is fully exploited (40-60% of unfished biomass)
B0_over <- 0.4*K #initial biomass (metric tons) if stock is over exploited (40% or less of unfished biomass)
B0_open <- 0.1*K #initial biomass (metric tons) for open access fisheries 

B_t <- 10000 #at time 1 B_t = B0

###Begin with catch = MSY
msy <- function(r, K, p){
  msy <- (r*K)/((p + 1)* exp((p + 1)/p))
  return(msy)
}

```

Try the equation:
```{r}
# Find msy:
H <- msy(r=r_slow, K=K, p=p)

# Use C=msy in the model with parameters defined above:
pt(B_t = B0_open, r = r_slow, K = K, p = p, H = H)

```

Now add time loop:
```{r}
# Define timescale (t)
tyears <- 50

#Create a loop for pt model
for(t in 2:tyears){
  B_t[t] <- pt(B_t = B_t[t-1], r = r_slow, K = K, p = p, H = H)
}

plot(B_t)
plot(H)

```

