---
title: "Chase Purrr and other tests 11/4"
author: "Chase Brewster"
date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(purrr)
library(repurrrsive)
library(tidyverse)
```

```{r}
# Operating model - this is our basic core model
## Initial version created 10/28 with help from Dan

##############################
# Step 1- Create df of experiments to run through the model
## Example for setup

n_experiment = 100 #Number of experiments we are running

experiment <- data.frame(
  b = runif(n_experiment, min = 1000, max = 100000),
  r = runif(n_experiment, min = 0.015, max = 1.15),
  r_s = runif(n_experiment, min = -0.015, max = 0.02),
  f = runif(n_experiment, min = .1, max = .6))
 # Here we are specifying the range for all the inputs we are varying in this model run
##############################
# Step 2 - define the simulation model

sim_fishery <- function(b, f, r, r_s, p, k, years){

  results <- data.frame(
    b = rep(NA, years), c = rep(NA, years), 
    year = 1:years, r = rep(NA, years), r_s = rep(NA, years), f = rep(NA, years)) #Setup the results dataframe where the outputs will be writen for however many years our experiment is running
  
  #Set the initial result for the outputs in year 1
  results$b[1] = b
  results$c[1] = f * b
  results$r[1] = r
  results$r_s[1] = r_s
  results$f[1] = f
  
  #Loop the model over the specified number of years
  for (t in 2:years) {
    
    results$c[t] = results$b[t-1] * f #define catch - won't need this if using the climate ready management below
    results$b[t] = results$b[t-1] + (results$r[t-1] / p)*results$b[t-1]*(1 - ((results$b[t-1]/k) ^ p))-results$c[t]#operating model-PT
    results$r[t] = results$r[1] * (1 + (r_s*(t-1))) #climate model - how does r change with climate change in each year
    results$r_s[t] = r_s
    results$f[t] = f
   } 
  
  return(results)
}

# Step 3 - Run the model for the experiments 

results = list() #we want the results to be outputted as a list

#Loop the simualation model over the experiments
for (i in 1:n_experiment){
  results[[i]] <- sim_fishery(b = experiment$b[i], f = experiment$f[i], r = experiment$r[i], r_s = experiment$r_s[i], p = 0.2,
                              years = 100, k = 100000)
}
#Note if you're getting a data has more rows type error you forgot to run the results = list() command first 

data <- data.frame(b_0 = experiment$b, r_0 = experiment$r, r_s = experiment$r_s, f = experiment$f) 

for(i in 1:100){
  data$b[i] <- list(results[[i]]$b)
  data$c[i] <- list(results[[i]]$c)
  data$year[i] <- list(results[[i]]$year)
}

plot(x = unlist(data$year), y = unlist(data$b), type = "l")



```


```{r}

#Going to try purrr again


```

